- FileTransfer/FileTransfer.h
Since the blackduck tool is super cryptic, I'm testing to see what the issue is.
> [blackduck] trying to figure out what is wrong

- SecurityAgent/AccessControlList.h
- SecurityAgent/example_acl.json
1) Fix regex match for allow/block filters.
2) Improve regex match for urls.
3) Fix example_acl.json to match the config in AccessControlList.h
> Improve regex match in SecurityAgent AccessControlList

- TraceControl/TraceControl.h
Reverts rdkcentral/ThunderNanoServices#52
> Revert "Development/trace buffers"

- Compositor/Compositor.cpp
- Compositor/Compositor.h
- Compositor/lib/Wayland/Wayland.cpp
- Compositor/lib/Wayland/Wayland.h
Currently the VirtualInput Switch is not get used by Wayland case, hence the SetInput has to be call specifically for Wayland. That support is added
> Compositor:Wayland:InputSelection support added

- examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp
- examples/OutOfProcessPlugin/OutOfProcessPlugin.cpp
The plugin hase been extended to demonstrate how the IPlugin::INotification sink can be used in an
out-of-process plugin. It was a use-case to resolve (at the end) 2 bugs. They are resolved in the
thunder core.
1) Missing AddRef/Release on the registration of these sinks, which would, after the registration
call delete the Proxies, and thus crash the system.
2) On the activation report of a plugin, the Service is locked. On the QueryInterface on this service
the same lock was used. Deadlock. However, this lock was just to protect the Inner Plugin from
being changed while the query interface on the inner object was being executed. The handling on the
inner object (shell -- Plugin) is now protected by a dedicated CriticalSection, effectively resolving
the deadlock
> [OUTOFPROCESSPLUGIN] Example plugin has been extended.

- IOConnector/IOConnector.cpp
- IOConnector/IOConnector.h
Also implemented the publishing/exposure of the IExternals available here to the ICatalog interface.
> [IExternal] Aligning to a slimmer interface. Remove and Rename.

- FirmwareControl/FirmwareControl.cpp
- FirmwareControl/FirmwareControl.h
Tracing sequence or info updated to avoid confusion in the sequences
> FirmwareControl: Tracing updates

- Power/Power.cpp
https://jira.rdkcentral.com/jira/browse/HP40A-198
> [Power] Align SetState with documentation

- Power/CMakeLists.txt
- Power/Implementation.h
- Power/Power.cpp
- Power/PowerImplementation/Broadcom/PowerImplementation.cpp
- Power/PowerImplementation/Linux/MFRPersistPower.cpp
- Power/PowerImplementation/Linux/PowerImplementation.cpp
- Power/PowerImplementation/Stub/MFRPersistPowerStub.cpp
- cmake/FindMFRPwrMgrLibs.cmake
Reason for change: Linux Implementation - Adding new feature of persistent power state (boot up from power loss in standby if device was in standby state).
Require: https://github.com/WebPlatformForEmbedded/meta-wpe/pull/469
Signed-off-by: Arun Madhavan <Arun_Madhavan@comcast.com>
> [Power] HP40A-126 : Power plugin - persistent state feature

- Compositor/Compositor.cpp
- Compositor/CompositorJsonRpc.cpp
- Compositor/doc/CompositorPlugin.md
- Compositor/lib/Nexus/NexusServer/NexusServer.cpp
- Compositor/lib/RPI/RPI.cpp
Updated Compositor Plugin JSON error value to align the changes in Compositor.json changes.
Currently the JSON error used ERROR_FIRST_RESOURCE_NOT_FOUND in case of client not found cases, so changed this to ERROR_UNAVAILABLE seems this value is more acceptable value
> Compositor: Updates based on change in JSON error value firstresourcenotfound to unavailable

- Power/Power.cpp
- Power/PowerImplementation/Broadcom/PowerImplementation.cpp
- Power/PowerImplementation/Linux/PowerImplementation.cpp
- Power/PowerJsonRpc.cpp
- Power/doc/PowerPlugin.md
Changed error types based on the error value changes in the Power.json.
> PowerControl: Updated SetState error type

- WebKitBrowser/WebKitBrowser.cpp
An earlier commit removed or reformatted notification messages. This PR will restore the original format.
> [BROWSER] Restores Notifications

- VolumeControl/AMLogic/VolumeControlPlatform.cpp
- VolumeControl/CMakeLists.txt
This PR adds the implementation of the VolumeControl plugin for the AMLogic platform, which links against the `libaudio_client.so`.
> [VolumeControl] Added AMLogic implementation

- DisplayInfo/Nexus/PlatformImplementation.cpp
Function declaration in IDisplayInfo.h inside Thunder repo did not match here. Correcting the function signature here
> Fixing mismatch in function signature

- ResourceMonitor/ResourceMonitor.cpp
- RtspClient/RtspClient.cpp
- Spark/Spark.cpp
- Streamer/Streamer.cpp
- VolumeControl/VolumeControl.cpp
- WebKitBrowser/WebKitBrowser.cpp
- WebPA/WebPA.cpp
- WebServer/WebServer.cpp
- examples/OutOfProcessPlugin/OutOfProcessPlugin.cpp
- examples/TestController/TestController.cpp
- examples/TestUtility/TestUtility.cpp
Make sure all plugins capable to run out of process are properly deactivated regardless for the respose of the Release method.
> Change deinitialize method in out of process plugins.

- IOConnector/GPIO.h
The interface has a new method, add it on the implementation.
This pull-request needs to go with: https://github.com/rdkcentral/ThunderInterfaces/pull/8
> [IOConnector] New method added. Supply empty metdata for now.

- WebServer/WebServerImplementation.cpp
This replaces PR https://github.com/rdkcentral/ThunderNanoServices/pull/128
The review comments in that one were not done yet and as it still was useful functionality to have we completed it.
> [WebServer] optional FileServer

- BluetoothControl/BluetoothControl.h
> For R2: BluetoothControl: Remove devices from list before scan.

- WebServer/WebServerImplementation.cpp
> [WebServer] Don't relay connection close header

- examples/JSONRPCPlugin/CMakeLists.txt
- examples/JSONRPCPlugin/JSONRPCPlugin.cpp
- examples/JSONRPCPlugin/JSONRPCPlugin.h
1. Removed unused variable warning 
2. Added proper classname for JSONRPCPlugin.config
> JSONRPCPlugin: Cleanups/Updates

- BluetoothAudioSink/BluetoothAudioSink.cpp
- BluetoothAudioSink/BluetoothAudioSink.h
- BluetoothAudioSink/ServiceDiscovery.h
- BluetoothAudioSink/SignallingChannel.h
- BluetoothAudioSink/TransportChannel.h
- BluetoothControl/BluetoothControl.h
Enable automatic connection of bonded audio sink device; workerpool-related changes; stability improvements...
> btaudio autoconnect

- BackOffice/BackOffice.cpp
- BackOffice/RequestSender.h
Fixed this PR: https://github.com/rdkcentral/ThunderNanoServices/pull/607
> Adjust headers send by the request sender

- BluetoothRemoteControl/BluetoothRemoteControl.cpp
- examples/MessageControlUDPClient/UDPMessageOutput.cpp
> Messaging improvements

- CECControl/adapter/CMakeLists.txt
- CECControl/adapter/device_adapter/CMakeLists.txt
- CECControl/adapter/device_adapter/test/CMakeLists.txt
- CECControl/adapter/processor/CMakeLists.txt
- CECControl/adapter/processor/test/CMakeLists.txt
- ResourceMonitor/CMakeLists.txt
- Snapshot/CMakeLists.txt
- SubsystemController/CMakeLists.txt
- WebProxy/CMakeLists.txt
- WebServer/CMakeLists.txt
Plugins only need to depend on the plugin module (this module will include all Thunder module)
> [TRANSFER] Move to the new messaging and drop the Tracing.

- .github/workflows/Build ThunderNanoServices on Linux.yml
[Plugins:-DPLUGIN_DIALSERVER=ON -DPLUGIN_DICTIONARY=ON]
> [Actions] Adding build parameters to allow selecting plugins

- .github/workflows/Build ThunderNanoServices on Linux.yml
[Options:-DPLUGIN_CECCONTROL=OFF]
> [Actions] Plugins enabled by default while using Options parameter

- BluetoothControl/BluetoothControl.cpp
- BluetoothControl/BluetoothControl.h
- BluetoothControl/Tracing.h
Also allow simultanous BLE and BR/EDR scanning.
requires https://github.com/WebPlatformForEmbedded/ThunderLibraries/pull/17
> [Bluetooth] Support advertising start/complete events

- Dictionary/Dictionary.cpp
- Dictionary/Dictionary.h
This PR requires this PR: https://github.com/rdkcentral/ThunderInterfaces/pull/267 to go first !
> [JSONPC] Update the implementation accordingly :-)

- BluetoothAudio/AudioEndpoint.h
- BluetoothAudio/BluetoothAudio.cpp
- BluetoothAudio/BluetoothAudioSink.h
- BluetoothAudio/BluetoothAudioSource.h
- BluetoothAudio/ServiceDiscovery.h
- BluetoothAudio/SignallingServer.h
> [BluetoothAudio] Support automatic session establishment on reconnection

- CMakeLists.txt
- Svalbard/CryptographyRPC.cpp
- Svalbard/Svalbard.conf.in
- Svalbard/Svalbard.cpp
- Svalbard/Svalbard.h
- VaultProvisioning/CMakeLists.txt
- VaultProvisioning/Implementation.cpp
- VaultProvisioning/Module.cpp
- VaultProvisioning/Module.h
- VaultProvisioning/VaultProvisioning.conf.in
- VaultProvisioning/VaultProvisioning.cpp
- VaultProvisioning/VaultProvisioning.h
Based on config VaultProvisioning will create a encrypted blob, that will be picked up by Svalbard on startup and loaded into the appropriate vault. Currently only provisioning of randomly generated key is supported.
> Introduce VaultProvisioning

- SubsystemController/SubsystemControl.cpp
note depends on: https://github.com/rdkcentral/Thunder/pull/1547
> [SubsystemController ] New installation subsystem

- CMakeLists.txt
This reverts commit a595492b13c40c25cd5c98fb5a8a562f3c5604f5.
> Revert "Update CMakeLists.txt (#799)"

- examples/CMakeLists.txt
- examples/PluginSmartInterfaceType/CMakeLists.txt
- examples/PluginSmartInterfaceType/Castor/CMakeLists.txt
- examples/PluginSmartInterfaceType/Castor/Castor.conf.in
- examples/PluginSmartInterfaceType/Castor/Castor.cpp
- examples/PluginSmartInterfaceType/Castor/Castor.h
- examples/PluginSmartInterfaceType/Castor/CastorImplementation.cpp
- examples/PluginSmartInterfaceType/Castor/CastorPlugin.json
- examples/PluginSmartInterfaceType/Castor/Module.cpp
- examples/PluginSmartInterfaceType/Castor/Module.h
- examples/PluginSmartInterfaceType/Pollux/CMakeLists.txt
- examples/PluginSmartInterfaceType/Pollux/Module.cpp
- examples/PluginSmartInterfaceType/Pollux/Module.h
- examples/PluginSmartInterfaceType/Pollux/Pollux.conf.in
- examples/PluginSmartInterfaceType/Pollux/Pollux.cpp
- examples/PluginSmartInterfaceType/Pollux/Pollux.h
- examples/PluginSmartInterfaceType/Pollux/PolluxImplementation.cpp
- examples/PluginSmartInterfaceType/Pollux/PolluxPlugin.json
Example for the PluginSmartInterfaceType
Introduced in this PR: https://github.com/rdkcentral/Thunder/pull/1694 so that one must be merged first
> [examples] add PluginSmartInterfaceType example

- BluetoothControl/BluetoothControl.h
- BluetoothControl/Tracing.h
this PR needs to wait untill https://github.com/rdkcentral/Thunder/pull/1755 is merged
> BluetoothControl: switch to BLUEZ_HAS_NO_INCLUSIVE_LANGUAGE define

- BluetoothControl/BluetoothControl.cpp
- BluetoothControl/BluetoothControl.h
Most changes are moving JSON types to C++ native types as the JSON is now autogenerated.
Needs https://github.com/rdkcentral/ThunderInterfaces/pull/392
> [BluetoothControl] Update to .json-free interface

- Compositor/lib/Mesa/backend/src/DRM/Connector.h
- Compositor/lib/Mesa/backend/src/DRM/DRM.cpp
- Compositor/lib/Mesa/backend/src/DRM/IGpu.h
- Compositor/lib/Mesa/backend/src/DRM/Legacy.h
- Compositor/lib/Mesa/backend/src/Wayland/IBackend.h
- Compositor/lib/Mesa/backend/src/Wayland/Output.cpp
- Compositor/lib/Mesa/backend/src/Wayland/Output.h
- Compositor/lib/Mesa/backend/src/Wayland/Wayland.cpp
- Compositor/lib/Mesa/include/IOutput.h
This reverts commit bccc6976d4013f63b5ff5844569162a7d53e06b6.
We need to give this change a bit more attention...
> Revert "[COMPOSITOR] One backend one Output. Multiple Outputs on the same bac… (#872)"

- RemoteControl/LinuxDevice.cpp
In case of keyboards or mouses which names does not contains words "keyboard" or "mouse" they are not recognized as input devices. To solve it we need to iterate through available devices with udev and add them based on properties like: ID_INPUT_KEYBOARD or ID_INPUT_MOUSE.
> [RemoteControl] fix keyboards and mouses detection
