- WifiControl/Network.cpp
Currently the WifiControl WPA-PSK mode is not working with WPA-PSK(TKP). Added required changes to support this as well.
> WifiControl: Add PROTO and PAIR keys with WPA-PSK support

- Spark/Spark.cpp
With latest pxcore library it need 3000 seconds to laugh Spark plugin
> Spark: RPC connection time need to be increaed with 1 more second

- NetworkControl/NetworkControl.cpp
- NetworkControl/NetworkControl.h
If start wlan0 in Dynamic mode with out a AP connected, this request will get failed and re request for IP using RequestFailed(). That will try to clear dispatcher using StopWatchdog(). But in this case this call will happened from the Dispatcher function only. Hence its creating a deadlock case.
> NetworkControl: avoid IP request from the dispatcher loop, since it ending with deadlock

- BluetoothControl/BluetoothControl.cpp
- BluetoothControl/BluetoothControl.h
- BluetoothControl/BluetoothControlJsonRpc.cpp
- TraceControl/TraceControl.h
BluetoothControl plugin is creating a static instance of ControlSocket. Its parent class is Opening and Closing SynchronousChannelType from the Cosntructor and Destructor. During the Exit sequence the SynchronousChannelType::Close is invoking from the destruction sequence (as part of linux process stack cleanup). In this case the SocketPorts are already terminated as part of termination cleanups from the WPEFramework,  hence it is waiting on an infinite loop.
If we make this class to non static it will be removed from the stack during the deactivation of Plugin itself.
> Bluetooth: avoid static instance of ControlSocket

- Compositor/Compositor.cpp
- Compositor/lib/Wayland/Wayland.cpp
In case of cobalt there is multiple surface for graphics and video. And these are prefixing by Callsign::layer: like Cobalt:graphics and Cobalt:video. But during the select application is sending only the callsign and hence the select will not work, since it could not able to find matching value.
> Compositor:Wayland: callsign search logic updated for Select

- DIALServer/DIALServer.cpp
- DIALServer/DIALServer.h
In slave mode, if the setting of url data to the application fails, it try it using the POST. But Currently in slave mode, we are registering the application handlers and all the url/data setting request to the app goes through the application handlers, and in slave mode the app instance will be always null and this sequence will never execute properly.
> DIALServer: Use Handler implementation only in master mode

- DIALServer/DIALServer.config
- DIALServer/DIALServer.cpp
The value of accessor host address is some time 0.0.0.0 or invalid, since these are getting prior to the NetworkControl up. So in this case the dialURL will be created using 0.0.0.0 host address and will not work. So start DIAL only once the Network interface up and ready and use the selected Host address to create dialURL
> DIALServer: add Network also the preconditions dependency

- IOConnector/GPIO.h
This is required to comply to the new IExternal interface found in this pull request: https://github.com/rdkcentral/Thunder/pull/117
> [IOConnector] Adaptions for the changes on the IExternal.

- NOTICE
BLDK-734:RDK License header changes-for Notice header update
Reason for change: RDK License header changes-for Notice header update
Test Procedure: Jenkin build should pass after License header changes for RDK for listed repos
Risks: None
> BLDK-724 License Text update in NOTICE file

- Power/Power.cpp
Issue: When HP40A device is put to STR and triggered Wake-Up, wake up sequence is not coming via Power plugin which results in not updating the persisted state.
Reason for change: Added persisted state update logic in power state change callback so that even hardware triggered state also gets updated.
Test Procedure: Put (HP40A)DUT in STR and trigger RCU/WoL wake-up, let device to be in ON state for few minutes. Then power cycle device. It shall boot to ON(last state); not to STR.
Risks: Low.
Signed-off-by: Arun P Madhavan <arun_madhavan@comcast.com>
> [Power] Persisted state not updated when resumed from STR

- FirmwareControl/DownloadEngine.h
- FirmwareControl/FirmwareControl.cpp
- FirmwareControl/FirmwareControl.h
- FirmwareControl/FirmwareControlJsonRpc.cpp
- FirmwareControl/doc/FirmwareControlPlugin.md
1. Changes to update download progress
2. Moved Hash value comparison logic to the FirmwareControl context, instead handling it from the webtransfer context (it helps to avoid delay in the json event notification during the Hash comparison)
> FirmwareControl: Change to update download progress to the initiated process

- RemoteControl/GreenPeak.cpp
This patch adds the missing return statement for LoadModule method.
The return statement was missing from this method and was thus returning
Junk values to the caller.
Most of the time we got `Core::ERROR_NONE/0` as the return so the code
worked.
If we get a junk value which is not 0. The GreenPeak producer will not
work.
Signed-off-by: harikrishnan.p <harikrishnan.p@tataelxsi.co.in>
> [RemoteControl] Add mising return statement for LoadModule in GreenPeak

- DIALServer/DIALServer.cpp
- DIALServer/Netflix.cpp
I thought windows (VS2019) is a pretty modern compiler but the dynamic allocation of arrays on a stack is not allowed. A I missing something. Used the old fashion ALLOCA() but please feedback if we could revert and have it compiling under windows as well..
> [WINDOWS] The windows compiler does not allow dynamic storage on stack.

- BluetoothControl/BluetoothControl.h
- BluetoothRemoteControl/T4HDecoders.cpp
- BluetoothRemoteControl/WAVRecorder.h
- DHCPServer/DHCPServerImplementation.h
- DIALServer/DIALServer.h
- DisplayInfo/DisplayInfoTracing.h
- IOConnector/IOConnector.cpp
- LocationSync/LocationService.h
- NetworkControl/DHCPClientImplementation.h
- OpenCDMi/CENCParser.h
- OpenCDMi/FrameworkRPC.cpp
- OpenCDMi/Module.h
- OpenCDMi/OCDM.cpp
- Packager/PackagerImplementation.h
- PlayerInfo/Dolby.h
- PlayerInfo/Dolby/include/Dolby.h
- Power/Implementation.h
- SecurityAgent/AccessControlList.h
- TimeSync/NTPClient.h
- WifiControl/Controller.cpp
- examples/FileTransferClient/FileTransferClient.cpp
- examples/JSONRPCPlugin/Data.h
- examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp
As there is no need to use plugins as librraies by other plugins, there is no need
to define any class to be externally accessible. This commit cleans all EXTERNAL
keywords still available on classes. This should be a very low risk as all the
Module.h files would already undefine EXTERNAL and set it to an empty value :-)
> [CLEANUP] Followup of the Module/rework cleanup on Thunder.

- IOConnector/IOConnector.config
Root cause: `pins` configuration expected is an array but single GPIO configuration is not creating it as array hence parse fails.
Fix logic: Forcing all `pins` configurations to be added as array in generated json.
Signed-off-by: Arun Madhavan <Arun_Madhavan@comcast.com>
> [IOConnector] Fix for Issue #161

- WifiControl/Controller.h
- WifiControl/WifiControlJsonRpc.cpp
- WifiControl/doc/WifiControlPlugin.md
1. Avoid Lock over ConnectRequest calls to avoid lock over Trigger() which end up with deadlock
2. Documentation in both WifiControlJsonRPC API description and WifiControl.md files are updated
> HP40A-217:Fix for Connect hang issue

- examples/JSONRPCClient/JSONRPCClient.cpp
- examples/JSONRPCPlugin/JSONRPCPlugin.cpp
- examples/JSONRPCPlugin/JSONRPCPlugin.h
- Corrected JSOPN RPC Server side Validation example to not make most of the other examples fail because of this ;) Added a special Validation test to the server and client 
- added specific call to better test Versioned calls
- repaired message send test
> [json rpc example] Fix and add functionality

- NetworkControl/DHCPClientImplementation.cpp
Seems some merge conflict happened DHCPClientImplementation.cpp with the PR(https://github.com/rdkcentral/ThunderNanoServices/pull/160). so correcting this
> NetworkControl: correct DHCPClientImplementation prototype

- Cobalt/Cobalt.config
Observed that some time Cobalt resume is either not loading the UI or just showing the loading screen.
This is happening if the Cobalt get activated before the Internet gets up. so adding this also into the dependency chain of Cobalt
> Cobalt: Add Internet also in the precondition list to avoid loading hangs

- WebKitBrowser/WebKitBrowser.cpp
- WebKitBrowser/WebKitBrowser.h
If we try to do the WebkitPlugin deactivation while the plugin is blocked state due to precondition not meet or similar reason, this endup with a crash of the WPEFramework. Currently we are doing the JSONRPC register only if the plugin instantiation is success. But the unregister is still handling from the WebKitBrowser destructor. So there is a chance to call UnregisterAll() with out doing the register and this is leading to the ASSERTION and  crashing the WPEFramework.
So better to make the Register and UnRegister sequences in. aligned way, hence the UnregisterAll() is moved to Deinitialization sequence.
> WebKitBrowser: move JSONRPC unregister calls from the destructor to deinitialize sequence

- ResourceMonitor/ResourceMonitor.config
QA can turn it on throught the ThunderUI
> By default do not start the resource monitor.

- ResourceMonitor/ResourceMonitor.h
The result string reported "Unknown request path specified." even on success.
> [RESOURCEMONITOR] Update result message string on success

- WebServer/WebServer.cpp
If the port of the Webserver can not be opened because it is already in use, report an error and do not silently continue.
> [WEBSERVER] Report an error scenario if it occures.

- DIALServer/DIALServer.cpp
It can be removed since now we are actually properly chacking it using the DIALServer::SafeOrigin method.
> Remove the "Terrible Hack" :-)

- WifiControl/WifiControl.cpp
- WifiControl/WifiControlJsonRpc.cpp
Currently we are saving the incomplete config during the error, so better to clear that entry
> WifiControl: remove incomplete config during update

- IOConnector/IOConnector.cpp
- IOConnector/IOConnector.h
The missing ICatalog::Resource() interface method is required for
directly getting the IExternal pointer to a give Pin ID, without having
to listen to ICatalog notifications.
> IOConnector: Implement the Resource() interface method

- DisplayInfo/CMakeLists.txt
- DisplayInfo/DisplayInfo.config
This fixes the parse error the DisplayInfo config would generate on Thunder startup (because an empty config section was generated), brings the in or out of process selection for the configuration in sync with how we do that for other plugins and makes the default selection now in process (previously it was not set in the config at all meaning it would be according the Thunder default  which is out of process.
(I must admit I would have had no clue how to fix it keeping it like it was and just not generating a config section at all when no setting inside it would have been selected :) )
> [DisplayInfo] fix config generation

- DIALServer/DIALServer.cpp
- DIALServer/DIALServer.h
If DIAL interface is set to 0.0.0.0 then the location IP for UPNP replies will be picked up from the interface the UPNP request was received on.
> [DIALServer] Dynamic location IP for UPNP replies

- BluetoothControl/BluetoothControl.h
Remove devices that are not connected and not bonded
before new scan is started.
> BluetoothControl: Remove devices from list before scan.

- DIALServer/DIALServer.cpp
At the moment the USN is not unique and does not contain a unique identifier (guess it was an oversight not to replace the UniqueID string with an actual ID).
This PR add the uuid (device id) to the USN. According to this information it is even mandatory to use the uuid:
http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0-20080424.pdf
" Note that the prefix of the USN header (before the double colon) must match the value of the UDN element in the device description. (The section on Description explains the UDN element.)"
https://williamboles.me/discovering-whats-out-there-with-ssdp/
> [DIAL] use uuid in USN

- DIALServer/DIALServer.h
Only if binding interface is set to 0.0.0.0 it is possible to change the locator host to the one from the UPNP request, in other cases (i.e from WebServer) only port is updateable.
> [DIALServer] Only allow chaning port of locator URL from external source

- WifiControl/Controller.h
- WifiControl/WifiControl.h
- WifiControl/WifiControlJsonRpc.cpp
Currently modifying existing config is not available - changes are present only in the plugin, not on disk so they are lost on restart.
> [WiFi] On config change delete old config and store new one

- WifiControl/WifiControl.h
This currently breaks the build therefore foxing in place
> [Wifi] Fix Interface map being private

- BluetoothRemoteControl/BluetoothRemoteControl.h
After analyzing the code used in BluetoothRemoteControl plugin, it was concluded that:
Find
FindHandle
FindChraracteristic
methods are better suited to be part of the core bluetooth implementaion, since the implementation is generic for any Bluetooth related plugin.
This patch removes these methods.
This should only be merged after https://github.com/rdkcentral/Thunder/pull/748
> Bluetooth Profile: Removing methods from BluetoothRemoteControl plugin

- examples/JSONRPCClient/CMakeLists.txt
The JSONRPCClient also has a dependency on the WebSocket library, all JSONRPCLink info is in there :-)
> [EXAMPLES] Add dependency on WebSocket for the JSONRPCClient app.

- IOConnector/GPIO.cpp
- IOConnector/GPIO.h
- IOConnector/IOConnector.cpp
- IOConnector/IOConnector.h
- IOConnector/TimedInput.h
This PR implements some fixes and rework to enable the use of the GPIO::Pin::TimedPin to correctly manage markers and notify observers.
It depends on https://github.com/rdkcentral/ThunderInterfaces/pull/112
> IOConnector: Fix and rework to enable the use of the TimedPin 

- BluetoothControl/BluetoothControl.h
Punch a hole in the scanning operation done by LE connect command, so simultaneous high bandwidth transfer (like audio streaming) is not clogged. 
This doesn't seem to have a negative impact on BT remote control connection or re-connection, but leaves enough link layer time for the audio stream to come through without stuttering.
> [BluetoothControl] Make the LE connect not block audio output

- NetworkControl/NetworkControl.h
- WifiControl/WifiControl.cpp
- WifiControl/WifiControl.h
- examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp
- examples/SimpleCOMRPCPluginServer/SimpleCOMRPCPluginServer.h
Jobs have now a more eleborated state, so the use of schedule is now
misleading as in the same time someone might have scheduled or submitted
it, the reschedule is mroe expected than a schedule. So lets change all
Schedules -> Reschedule.
> [WORKERPOOL] Schedule method on JobType's is obsolete.

- RemoteControl/RemoteControl.cpp
Fixing potential deadlock when registering/unregistering for events, where if notification client is already listed/non-existing it would leave the Core::CriticalSection _eventLock in permanent lock state, thus locking all event notifications.
> RemoteControl: Fix potential deadlock

- BluetoothControl/BluetoothControl.h
So we can successfully connect when it is the (previously unknown) remote device that initiates connection.
> [BluetoothControl] Consider a device that attempts a connection known

- IOConnector/TimedInput.h
This PR brings in the below commits
5c1c8d9a58421d87986af34890972139e3a3afd9 : Fix issue where notification is not sent for last marker in list
e57cb3c2a150d0213b7d1230c088260aca2df722 : Handle key release without key press scenario
> IOConnector: Handle key release without key press scenario

- WifiControl/WifiControlImplementation.cpp
This issue was only present when trying to run Thunder with WifiControl plugin enabled on devices without a wireless network card, so for example on Ubuntu VM with NAT. In this case, it is not possible to enable wpa_supplicant on a proper interface (since the wireless network card is not there), so the plugin fails to initialize, and then it crushes Thunder in Debug mode when an assert fires. It is now fixed with a simple conditional statement.
> Making sure that failing WifiControl plugin won't break Thunder

- BluetoothControl/BluetoothControl.cpp
- BluetoothControl/BluetoothControl.h
Since it often happens on Pi, don't crash because of this.
[Options:-DPLUGIN_CECCONTROL=OFF]
> [BluetoothControl] Don't assert on failed adapter init

- .github/workflows/Build ThunderNanoServices on Linux.yml
- .github/workflows/Linux build template.yml
Same as with the Thunder PR: https://github.com/rdkcentral/Thunder/pull/1496
This is an initial pull request - the new workflows have to be called from my branches for now (there is a dependency between the workflows), since we need to first merge new templates in each repo. Then, I'll make one more set of pull requests to redirect this new feature to master branches of our repos.
Required checks got updated to the new ones by Stephen.
> [Actions] Managing dependencies to make the workflows callable from different repos

- .github/workflows/Build ThunderNanoServices on Linux.yml
The last set of pull requests, now the new Actions will use workflows from our repos instead of my forks, which sadly couldn't have been done in one go.
> [Actions] Using the already merged workflows instead of my forks

- Compositor/lib/RPI/RPI.cpp
- Compositor/lib/Wayland/Wayland.cpp
Some implementations were setting the Platform subsystem without providing a actual platform server.
> Compositor: don't set the PLATFORM subsystem

- NetworkControl/NetworkControl.conf.in
now you can just configure cmake with ```-DPLUGIN_NETWORKCONTROL_INTERFACES="eth0|wlan0"``` to have DHCP on those interfaces. This is what you want 9/10 times. 
Specific config is still possible by using ```-DPLUGIN_NETWORKCONTROL_INTERFACES="eth0;Static;10.0.0.1;24;10.0.0.254;AA:BB:CC:DD:EE:FF|wlan0;Dynamic;;;;FF:EE:DD:CC:BB:AA"```
> NetworkControl: cmake relax interface dhcp configuration

- .github/workflows/Build ThunderNanoServices on Linux.yml
The proper branch checkout had to be done in two separate steps so that we didn't need to include the repo admins to bypass the required checks
> [Actions] Using the build template from master after the checkout fix

- .github/workflows/Build ThunderNanoServices on Linux.yml
- .github/workflows/Linux build template.yml
Now with the Bluetooth extension with audio and GATT support building in Thunder, we can add all of the Bluetooth plugins to the Linux workflow (a required check)
> [Actions] Build all of the Bluetooth plugins

- NetworkControl/NetworkControlImplementation.cpp
If the /etc/resolve.conf file (typeically the DNS file) does not exist or is empty, in debug, an ASSERT fires in the DateElement since one triees to access an empty buffer. While fixing this also found that there is already a Search for pattern method in the DataElement, so start using it. Prune where you can prune ;-)
> [NETWORKCONTROL] Also cope with DNS files that have a size of 0..

- WebServer/WebServer.cpp
- WebServer/WebServer.h
- WebServer/WebServerImplementation.cpp
METROL-1061 WebServer crashes during deactivation because of assertions
> [WebServer] fix deactivate issues

- Power/PowerImplementation/Linux/PowerImplementation.cpp
- examples/CMakeLists.txt
METROL-1062 Power plugin crashes if it is deactivated and then activated again
> [Power] Fix restart issue

- .github/workflows/Build ThunderNanoServices on Linux.yml
- .github/workflows/Linux build template.yml
- BluetoothControl/BluetoothControl.h
- DHCPServer/DHCPServerImplementation.h
It looks like compiler got this one warning wrong, and for some reason only in Release and not in Debug. In this case, `memcpy` cannot write to the `uint8_t _buffer[maxLength]` more than the `_buffer` can handle, as it will only write to the buffer if `_length <= maxLength`, so I think it is safe to disable this warning (it has to be on the whole constructor otherwise the warning is still there)
```
FAILED: DHCPServer/CMakeFiles/ThunderDHCPServer.dir/DHCPServer.cpp.o 
/usr/bin/c++ -DBLUEZ_HAS_NO_INCLUSIVE_LANGUAGE -DNO_INCLUSIVE_LANGUAGE -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderDHCPServer_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_BLUETOOTH_SUPPORT__ -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem …
```
> [Actions] Patch the Linux workflows after GitHub runners update, disable one warning

- .github/workflows/Build ThunderNanoServices on MacOS.yml
Otherwise it clashes with the Linux required checks, even despite the workflow name being different
> [Actions] Make sure all MacOS job names are unique

- BluetoothRemoteControl/4ModDecoders.cpp
- BluetoothRemoteControl/Administrator.cpp
- BluetoothRemoteControl/Administrator.h
- BluetoothRemoteControl/BluetoothRemoteControl.cpp
- BluetoothRemoteControl/BluetoothRemoteControl.h
- BluetoothRemoteControl/BluetoothRemoteControlPlugin.json
- BluetoothRemoteControl/T4HDecoders.cpp
- BluetoothRemoteControl/doc/BluetoothRemoteControlPlugin.md
Needs https://github.com/rdkcentral/ThunderInterfaces/pull/405
> [BTRemoteControl] Reinstate IVoiceHandler support

- ResourceMonitor/ResourceMonitorImplementation.cpp
Necessary to get rid of deprecated warnings treated as errors after [this](https://github.com/rdkcentral/Thunder/pull/1865) PR to Thunder
> [ResourceMonitor] Replace each process_t with pid_t

- Compositor/lib/Mesa/Compositor.cpp
- Compositor/lib/Mesa/renderer/test/testclear.cpp
- Compositor/lib/Mesa/renderer/test/testdmabuf.cpp
- Compositor/lib/Mesa/renderer/test/testquads.cpp
- Compositor/lib/Mesa/renderer/test/testtexture.cpp
This fixes some weird glitching with WebGL
> [Compositor] Framebuffer unbinding should occur before committing output
